//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int IdOffer { get; set; }
        public int EmployeeIdUser { get; set; }
        public int ListingIdListing { get; set; }
        public double Price { get; set; }
        public bool HasTools { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Listing Listing { get; set; }
    }
}
