//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Offer
    {
        [DataMember]
        public int IdOffer { get; set; }
        [DataMember]
        public int EmployeeIdUser { get; set; }
        [DataMember]
        public int ListingIdListing { get; set; }
        [DataMember]
        public double Price { get; set; }
        [DataMember]
        public bool HasTools { get; set; }
        [DataMember]
        public bool IsAccepted { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual Listing Listing { get; set; }
    }
}
