//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int IdReview { get; set; }
        public int Grade { get; set; }
        public string Comment { get; set; }
        public int UserIdUser { get; set; }
    
        public virtual User UserReviewer { get; set; }
        public virtual User UserReviewed { get; set; }
    }
}
