//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int IdTransaction { get; set; }
        public System.DateTime Time { get; set; }
        public string Balance { get; set; }
        public int UserIdPaid { get; set; }
        public int UserIdPaidTo { get; set; }
        public string Note { get; set; }
    
        public virtual User UserPaid { get; set; }
        public virtual User UserPaidTo { get; set; }
    }
}
